apiVersion: v1
kind: Job
metadata:
  name: multiply
  namespace: default
spec:
  cudaFilePath: /root/MiniK8S/cuda/multiply/multiply.cu
  resultFileName: result
  resultFilePath: /root/MiniK8S/cuda/multiply
  args:
    cpusPerTask: 1


