apiVersion: v1
kind: HPA
metadata:
  name: nginx-hpa
spec:
  maxreplicas: 10
  minreplicas: 1
  scaletargetref:
    kind: deployment
    name: nginx-dp
    apiVersion: v1
  behavior:
    scaledown:
      policies:
        - type: percent
          value: 50
          periodSeconds: 15
      selectpolicy: max
      stabilizationwindowseconds: 120
    scaleup:
      policies:
        - type: percent
          value: 100
          periodSeconds: 15
      selectpolicy: max
      stabilizationwindowseconds: 10
  metrics:
    - type: cpu
      target: 1
      