apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: example
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    cmd:
    - tail
    - -f
    - /dev/null
    volumeMount:
    - name: volume1
      mountPath: /tmp/volume1
    - name: volume2
      mountPath: /tmp/volume2

  - name: centos
    image: centos:latest
    cmd:
    - tail
    - -f
    - /dev/null
    volumeMount:
    - name: volume1
      mountPath: /tmp/tmp/volume1
    - name: volume2
      mountPath: /tmp/tmp/volume2

  - name: http-echo
    image: hashicorp/http-echo:latest
    volumeMount:
    - name: volume1
      mountPath: /tmp/volume1
    - name: volume2
      mountPath: /tmp/volume2

  - name: apache
    image: httpd:latest

  volumes:
  - name: volume1
    persistentVolumeClaim: ""
  - name: volume2
    persistentVolumeClaim: ""

